include_guard()

function(DetectSystemParams)

  # Detect architecture from CMAKE_SYSTEM_PROCESSOR.
  if(NOT DEFINED WYVERN_ARCHITECTURE)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64")
      set(WYVERN_ARCHITECTURE "x86_64")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "i[3-6]86|x86")
      set(WYVERN_ARCHITECTURE "i386")
    elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64|ARM64")
      set(WYVERN_ARCHITECTURE "aarch64")
    else()
      set(WYVERN_ARCHITECTURE "${CMAKE_SYSTEM_PROCESSOR}")
    endif()
  endif()

  if(NOT DEFINED WYVERN_LITTLE_ENDIAN)
    include(TestBigEndian)
    test_big_endian(BIGENDIAN)
    if(NOT BIGENDIAN)
      set(WYVERN_LITTLE_ENDIAN TRUE)
    else()
      set(WYVERN_LITTLE_ENDIAN FALSE)
    endif()
  endif()

  if(NOT DEFINED WYVERN_SYSTEM)
    if(WIN32)
      set(WYVERN_SYSTEM "windows")
    elseif(APPLE AND ${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
      set(WYVERN_SYSTEM "macos")
    elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
      set(WYVERN_SYSTEM "linux")
    elseif(UNIX)
      set(WYVERN_SYSTEM "unix")
    else()
      set(WYVERN_SYSTEM "unknown")
    endif()
  endif()

  if(NOT DEFINED WYVERN_SYSTEM_FAMILY)
    if(WIN32)
      set(WYVERN_SYSTEM_FAMILY "windows")
    elseif(UNIX)
      set(WYVERN_SYSTEM_FAMILY "unix")
    else()
      set(WYVERN_SYSTEM_FAMILY "unknown")
    endif()
  endif()

  if(NOT DEFINED WYVERN_COMPILER)
    if(NOT CMAKE_C_COMPILER_ID STREQUAL CMAKE_CXX_COMPILER_ID)
      message(FATAL_ERROR "C and C++ compiler id do not match, unsupported build configuration")
    endif()

    if(CMAKE_C_COMPILER_ID STREQUAL "Clang" OR CMAKE_C_COMPILER_ID STREQUAL "AppleClang")
      set(WYVERN_COMPILER "clang")
    elseif(CMAKE_COMPILER_IS_GNUC)
      set(WYVERN_COMPILER "gnu")
    elseif(MSVC)
      set(WYVERN_COMPILER "msvc")
    else()
      string(TOLOWER "${CMAKE_C_COMPILER_ID}" WYVERN_COMPILER)
    endif()
  endif()

  # Enable OPTIONs based on the discovered system / environment.
  if(WYVERN_COMPILER STREQUAL "gnu")
    option(WYVERN_ENABLE_STATIC_LIBGCC_LIBSTDCXX "Statically link libgcc and libstdc++" OFF)
    option(WYVERN_ENABLE_GCC_PROFILING "Enable gcc/g++ profiling via the -pg flag" OFF)
    option(WYVERN_ENABLE_GLIBCXX_DEBUG "Enable _GLIBCXX_DEBUG for g++" OFF)
  endif()

  if(WYVERN_COMPILER STREQUAL "msvc")
    option(WYVERN_ENABLE_STATIC_MSVC_RUNTIME "Statically link with the CRT" OFF)
  endif()

  message(STATUS "Architecture: ${WYVERN_ARCHITECTURE}")
  message(STATUS "Little Endian: ${WYVERN_LITTLE_ENDIAN}")
  message(STATUS "System: ${WYVERN_SYSTEM}")
  message(STATUS "System family: ${WYVERN_SYSTEM_FAMILY}")
  message(STATUS "C/C++ compiler: ${WYVERN_COMPILER}")

  # Set a cmake CACHE variable and define a corresponding C/C++ definition.
  # Using CACHE INTERNAL so the variable is visible outside this function.
  function(_wyvern_set_flag flagValue)
    set(${flagValue} TRUE CACHE INTERNAL "" FORCE)
    add_definitions(-D${flagValue})
  endfunction()

  if(WYVERN_LITTLE_ENDIAN)
    _wyvern_set_flag(WYVERN_LITTLE_ENDIAN)
  else()
    _wyvern_set_flag(WYVERN_BIG_ENDIAN)
  endif()

  if(WYVERN_ARCHITECTURE STREQUAL "i386")
    _wyvern_set_flag(WYVERN_ARCHITECTURE_I386)
  elseif(WYVERN_ARCHITECTURE STREQUAL "x86_64")
    _wyvern_set_flag(WYVERN_ARCHITECTURE_X86_64)
  endif()

  if(WYVERN_SYSTEM STREQUAL "windows")
    _wyvern_set_flag(WYVERN_SYSTEM_WINDOWS)
  elseif(WYVERN_SYSTEM STREQUAL "macos")
    _wyvern_set_flag(WYVERN_SYSTEM_MACOS)
  elseif(WYVERN_SYSTEM STREQUAL "linux")
    _wyvern_set_flag(WYVERN_SYSTEM_LINUX)
  endif()

  if(WYVERN_SYSTEM_FAMILY STREQUAL "windows")
    _wyvern_set_flag(WYVERN_SYSTEM_FAMILY_WINDOWS)
  elseif(WYVERN_SYSTEM_FAMILY STREQUAL "unix")
    _wyvern_set_flag(WYVERN_SYSTEM_FAMILY_UNIX)
  endif()

  if(WYVERN_COMPILER STREQUAL "gnu")
    _wyvern_set_flag(WYVERN_COMPILER_GNU)
  elseif(WYVERN_COMPILER STREQUAL "clang")
    _wyvern_set_flag(WYVERN_COMPILER_CLANG)
  elseif(WYVERN_COMPILER STREQUAL "msvc")
    _wyvern_set_flag(WYVERN_COMPILER_MSVC)
  endif()
endfunction()
